In [1]:
import numpy as np

In [11]:
v = np.array([[10000, 10010, 10],
              [10, 10, 10]])

b, n = v.shape

In [25]:
exponented = np.exp(v - v.max(axis=1).reshape((b, 1)))
exponented / exponented.sum(axis=1).reshape((b, 1))

array([[4.53978687e-05, 9.99954602e-01, 0.00000000e+00],
       [3.33333333e-01, 3.33333333e-01, 3.33333333e-01]])

In [26]:
mu, sigma = 0, 1
batch_size = 10
input_size = 748
num_hidden = 100
W1 = np.random.normal(mu, sigma, (input_size, num_hidden))
data = np.random.normal(mu, sigma, (batch_size, input_size))

In [31]:
from nn import sigmoid

In [28]:
data.shape, W1.shape

((10, 748), (748, 100))

In [33]:
sigmoid(data @ W1).shape

(10, 100)

In [30]:
(data @ W1).shape

(10, 100)

In [3]:
from nn import forward_prop, get_initial_params, read_data, one_hot_labels, sigmoid, softmax

In [118]:
import numpy as np
np.random.seed(100)
data, labels = read_data('./images_train.csv', './labels_train.csv')
labels = one_hot_labels(labels)
p = np.random.permutation(1000)
data = data[p,:]
labels = labels[p,:]

In [119]:
params = get_initial_params(784, 100, 10)
hidden = sigmoid(data @ params['W1'] + params['b1'])

c:\Users\azh.makanov\Documents\courses\cs229-2021\ps2\src\mnist\nn.py:43: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))


In [120]:
output = softmax(hidden @ params['W2'] + params['b2'])

In [121]:
eps = 1e-6
np.log(output + eps)

array([[ -0.73306352, -10.47843428,  -0.65953724, ...,  -7.58747749,
        -13.59343457, -13.81546419],
       [ -0.06802578, -13.81542896,  -2.72794175, ..., -11.22443678,
        -10.52774566, -13.81546631],
       [ -0.11217017, -13.63531021,  -2.25020842, ..., -13.79112232,
        -13.8154935 , -13.81551051],
       ...,
       [ -1.67800766, -13.81399806,  -3.31262106, ...,  -7.55428797,
        -13.48654354, -13.50085361],
       [ -0.07650664, -13.81525658,  -6.80102669, ...,  -4.11122603,
        -13.78372985,  -6.97379604],
       [ -2.90530968, -13.81101127, -11.00137705, ...,  -4.74513831,
        -11.23143202, -13.81550926]])

In [122]:
labels * np.log(output + eps)

array([[ -0.73306352,  -0.        ,  -0.        , ...,  -0.        ,
         -0.        ,  -0.        ],
       [ -0.        ,  -0.        ,  -0.        , ..., -11.22443678,
         -0.        ,  -0.        ],
       [ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
         -0.        ,  -0.        ],
       ...,
       [ -0.        , -13.81399806,  -0.        , ...,  -0.        ,
         -0.        ,  -0.        ],
       [ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
        -13.78372985,  -0.        ],
       [ -0.        ,  -0.        ,  -0.        , ...,  -0.        ,
         -0.        , -13.81550926]])

In [123]:
loss = - (labels * np.log(output + eps)).mean()
loss

0.9308363866511425

In [124]:
dW2 = hidden.T @ (output - labels)
dW2.shape

(100, 10)

In [125]:
db2 = (output - labels).sum(axis=0)
db2.shape

(10,)

In [126]:
# (hidden * (1-hidden)).shape, (hidden * (1-hidden)).sum(axis=0)

In [127]:
hidden * (1-hidden)

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        1.06136693e-003, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        9.56702213e-008, 0.00000000e+000, 0.00000000e+000],
       ...,
       [0.00000000e+000, 2.03109741e-002, 0.00000000e+000, ...,
        2.35677071e-001, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        5.02075057e-308, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 1.27523911e-188]])

In [132]:
(hidden * (1-hidden)).sum(axis=0).shape

(100,)

In [141]:
H = 100
s = np.zeros((H, H))
np.fill_diagonal(s, np.diag(hidden.T @ (1-hidden)))

In [142]:
s

array([[3.36504483e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.48183588e-01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.11869206e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.65639553e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.60712046e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 8.43117163e-07]])

In [99]:
# s = (hidden * (1-hidden)) #.sum(axis=0).reshape((100, 1))

s.shape, data.shape, output.shape, params['W2'].shape
# s

((100, 100), (60000, 784), (60000, 10), (100, 10))

In [100]:
dW1 = (data.T @ (output - labels) @ params['W2'].T) @ s
dW1.shape

(784, 100)

In [106]:
db1 = ((output - labels) @ params['W2'].T @ s).sum(axis=0)
db1.shape

(100,)

In [110]:
def gradient(f, value, delta=1e-3):
    return (f(value + delta) - f(value - delta)) / (2*delta)

In [ ]:

def backward_prop(data, labels, params, forward_prop_func):
    hidden, output, loss = forward_prop_func(data, labels, params)
    dW2 = ((output - labels).T @ hidden).T
    db2 = (output - labels).sum(axis=0)
    _, H = hidden.shape
    s = np.zeros((H, H))
    np.fill_diagonal(s, (hidden * (1-hidden)))
    dW1 = (data.T @ (output - labels) @ params['W2'].T) @ s
    db1 = ((output - labels) @ params['W2'].T @ s).sum(axis=0)
    return 
